### ISSUE TITLE
disable commits

### ISSUE THREAD

**Issue by sull** [ttskch/ghsync#5]
This is interesting, might try it out. Thoughts on a mode to disable commits (ignore changes on local) and only pull down changes detected on github repo? I have a situation where that control in some cases would be useful.

**Comment by ttskch** [comment]
@sull I think you can ignore all changes on local by configuring `repos[].ignores` in [~/.config/ghsync/default.yml](https://github.com/ttskch/ghsync/blob/master/config/default.yml.placeholder#L4) like below:

```yml
repos:
  - remote: {owner}/{repo}
    local: /path/to/local/repo
    ignores:
      - **
```

Please try it.
